### PR TITLE
Update .replit

### PR DESCRIPTION
**Pull request by KianiDev**
Added full .replit config to prevent Replit make a new one with an incorrect path to index.js.

### CODE REVIEW

**Comment by SheepTester** [comment]
that's a lot of lines, what do they do? or is this copypasted from an example in their documentation or something?

**Comment by KianiDev** [comment]
They are created by Replit, I changed some paths to index.js to prevent errors.

**Comment by KianiDev** [comment]
The Replit looks at the root folder of the project for the index.js file, which makes an error. I fixed that.

**Comment by KianiDev** [comment]
If needed, I'll remove the other codes, but the entrypoint is needed to fix the issue.

**Comment by SheepTester** [comment]
Thanks for simplifying the file; I'll merge it now :)

**Pull request merged**
